name: Deploy To Vercjames DO Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Transfer Source Code
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          key: ${{ secrets.UBUNTU_SSHPRIVATE }}
          username:  ${{ secrets.UBUNTU_USERNAME }}
          password:  ${{ secrets.UBUNTU_PASSWORD }}
          port: ${{ secrets.UBUNTU_PORT }}
          source: "."
          target: "/www/public.vercjames.com"

      - name: Install Dependencies and Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          key: ${{ secrets.UBUNTU_SSHPRIVATE }}
          username:  ${{ secrets.UBUNTU_USERNAME }}
          password:  ${{ secrets.UBUNTU_PASSWORD }}
          port: ${{ secrets.UBUNTU_PORT }}
          script: |
            cd /www/public.vercjames.com
            pm2 delete public.vercjames.com || true 
            pm2 start "yarn next start -p 3001" --name "public.vercjames.com"
            pm2 save
